name: Replace Image
description: Replaces a wiki image with the one from the given URL.
title: "Image Replacement"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        This also replaces all uses of the image in the wiki. Both images
        need to have different extensions. If you want to replace an image
        with the same extension use the wiki directly.
  - type: dropdown
    id: task
    attributes:
      label: Task
      multiple: false
      options:
        - replaceImage
      default: 0
    validations:
      required: true
  - type: dropdown
    id: wiki
    attributes:
      label: Wiki
      multiple: false
      options:
        - Pathfinderwiki
        - Starfinderwiki
      default: 0
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: Image
      description: The wiki image to replace.
      placeholder: e.g. File:In the Footsteps of Horror.jpg
    validations:
      required: true
  - type: input
    id: replaceWith
    attributes:
      label: Replace With
      description: A full URL to the image that should replace the wiki image.
      placeholder: e.g. https://mypage/image.webp
    validations:
      required: true
