name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
    - name: Dispatch wiki deployment
      uses: actions/github-script@v6
      if: github.ref == 'refs/heads/main'
      with:
        github-token: ${{ secrets.DISPATCH_PAT }}
        script: |
          const result = await github.rest.repos.createDispatchEvent({
            owner: 'pf-wikis',
            repo: 'wikis',
            event_type: 'bots_release',
            client_payload: {}
          })
          console.log(result);
