name: Run hourly bots

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
    - name: News Feed Reader
      run: java -jar target/bots-0.0.0.jar news-feed-reader --password ${{ secrets.ROOT_BOT_PW }} --discordToken ${{ secrets.DISCORD_TOKEN }}
    - name: Page Syncer
      run: java -jar target/bots-0.0.0.jar page-syncer --password ${{ secrets.ROOT_BOT_PW }} --discordToken ${{ secrets.DISCORD_TOKEN }}
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: current
    - name: Template Styles
      run: |
        npm install less -g
        java -jar target/bots-0.0.0.jar template-styles --password ${{ secrets.ROOT_BOT_PW }} --discordToken ${{ secrets.DISCORD_TOKEN }}
        chown -R www-data:www-data outputs
    - name: Copy styles to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "outputs/*"
        target: /wikis/volumes/bots

    # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
